# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2f93e55a6d2e5da0303a856763c444fb168d9cca00539615b7db5d6975215bfe2df9a49448100abe7f4156fdd7316ddd52025283b1647928716a85271428277

test:
  secret_key_base: 424119bcad0ebb385a357115027e80b09d6ad1345f52e74ad54f1e59fc7c654387345cee2701795e6f306cae2667b3e7801c65d04c8318b02ee281192052669e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
